import React from 'react'
import SecFull from './SecFull'
import Section from './Section'
import SectionPhoto from './SectionPhoto'
import Footer from './Footer'
import t1i1 from '../topic1Photos/Picture1.jpeg'
import t1i2 from '../topic1Photos/Picture2.jpg'
import t1i3 from '../topic1Photos/Picture3.png'
import t1i4 from '../topic1Photos/Picture4.jpg'

const Topic1 = () => {


    const rowStyle = {
        display: 'flex',
        justifyContent: 'center',
        padding: '5% 5%',
        flexDirection: 'row',
        flexWrap: 'wrap'

    }
    const pageStyle = {
        paddingTop: '20px',
        marginBottom: '0px',
        paddingBottom: '30px'
    }

    var refs = ['Chelsea GIS. (2008). Geographic Information System (GIS). City of Chelsea MA. Retrieved August 6, 2022, from https://www.chelseama.gov/information-technology/pages/geographic-information-system-gis',
        'Current Results. (2022). Phoenix temperatures: Averages by month. Phoenix AZ Average Temperatures by Month - Current Results. Retrieved August 5, 2022, from https://www.currentresults.com/Weather/Arizona/Places/phoenix-temperatures-by-month-average.php',
        'Geodataplus. (2022). ZIP code 85007 property data. GeoData Plus Zip Code 85007 Property Data. Retrieved August 5, 2022, from https://www.geodataplus.com/property-data/arizona/85007',
        'Griggs, B. (2021, June 23). Boston air travel volumes to take 3-5 years to rebound, Massport says. WCVB. Retrieved August 6, 2022, from https://www.wcvb.com/article/boston-logan-airport-travel-volumes-3-to-5-years-rebound-massport/36082055#',
        'McEwan, G. (2020, January 23). Are canopy cover targets the best way to maximise the benefits of trees? HortWeek. Retrieved August 4, 2022, from https://www.hortweek.com/canopy-cover-targets-best-maximise-benefits-trees/arboriculture/article/1660000',
        'Moutinho, S., & Gawthrop, E. (2021, March 1). Dangerous heat, unequal consequences: How Two neighborhoods in Arizona and Florida became hotspots for Sickening heat. WUSF Public Media. Retrieved August 5, 2022, from https://wusfnews.wusf.usf.edu/environment/2021-01-24/dangerous-heat-unequal-consequences-how-two-neighborhoods-in-arizona-and-florida-became-hotspots-for-sickening-heat',
        'Samuels, M. (2019, November 18). Community noise lab works with communities affected by Noise Pollution. Boston University. Retrieved August 1, 2022, from https://www.bu.edu/articles/2019/community-noise-lab/',
        'Sound Proofing Guide. (2022, June 12). Levels of noise in decibels (DB) level comparison chart. Sound Proofing Guide. Retrieved August 4, 2022, from https://soundproofingguide.com/decibels-level-comparison-chart/',
        'U.S. Census. (2022). U.S. Census Bureau quickfacts: United States. United States Census . Retrieved August 6, 2022, from https://www.census.gov/quickfacts/fact/table/US/RHI125221',
        'U.S. DoT. (2022). The train horn rule and quiet zones. The Train Horn Rule and Quiet Zones | FRA. Retrieved August 6, 2022, from https://railroads.dot.gov/highway-rail-crossing-and-trespasser-programs/train-horn-rulequiet-zones/train-horn-rule-and-quiet#:~:text=Under%20the%20Train%20Horn%20Rule,of%20all%20public%20grade%20crossings.',
        'WPR. (2022). Chelsea, Massachusetts population 2022. Chelsea, Massachusetts Population 2022 (Demographics, Maps, Graphs). Retrieved August 6, 2022, from https://worldpopulationreview.com/us-cities/chelsea-ma-population '
        ]

    return(
        
        <div style={pageStyle}>
            <a  href= '../' className="Button"> ↩ Back
            </a>
            <div className='h2'>
            The Impact of Race & Socioeconomic Class in the U.S.A. 
            </div>
            
            <div style={rowStyle}>
            <Section sectionPic={t1i1} sectionTitle={'Introduction'} sectionContent={'\t Noise Pollution: The sound levels that we experience are not only a perceived nuisance, but actually a threat to our health and wellbeing. This is related to the global climate crisis as new (and old) infrastructure is built to improve efficiency and reduce overall emissions. The people who are affected by this development are the people paying a hidden cost as a result. While our example is zooming in on one concentrated example of this phenomenon, this concept can be extrapolated to nearly all urban settings. People of colour and lower socioeconomic classes are funneled into this high traffic, highly noise polluted areas and endure far worse conditions than others. Experiencing only 65 decibels, roughly the noise generated by a passing car, for extended periods of time increase risk of hypertension and heart attack (Samuels, 2019). Not to mention the effect that high noise levels have on your quality of sleep. The WHO (World Health Organization) recommended nighttime outdoor noise level is 40 decibels, this is also endorsed by other policy making health organizations.  Ambient Temperature: The forecasted temperature for a given city, region, or area are a good indication for what to expect when going outdoors. Although, something that is overlooked is the experienced surface temperature. This is rarely measured officially, although the sensation to seek shade under a tree on the grass is a perfect example of how we cope with the heat. This sub-topic is more directly tied to the global climate crisis as global warming and ever-increasing temperatures hit certain areas particularly hard. When we compare the blacktop of a parking lot or highway to a frying pan, this is because it feels hotter than the adjacent grass or shaded pavement. While the stark contrast of green between my next examples are easily differentiated, access and abundance of greenspaces, mature trees and green residential grass can be found elsewhere. The primary reason this occurs is because some areas put the burden of maintenance of trees on the residents rather than the municipality (like here in Calgary). This means that despite the efforts of urban tree planting programs, achieving the level of canopy coverage that mature trees do is unlikely without water subsidies. '}/>
            <Section sectionPic={t1i2} sectionTitle={'Chelsea, Massachusetts'} sectionContent={'In Chelsea Massachusetts there is a major noise pollution problem. A major contributing factor is the loud infrastructure that surrounds it as well as a lack of policy controlling when certain like trains and airplanes can opperate. Please see the map below, as you can see there is the Mystic and Chelsea River that act as a channel for ships to use to deliver goods. There is also a massive six-lane highway called the Northeast Expressway, as well as a railroad in which trains are required to sound to their horn when entering the municipality (U.S. DoT, 2022). Finally, and the loudest with the most frequency of high amounts of noise, is the Boston Logan International Airport with roughly 1,200 inbound and outbound flights every day (Griggs, 2021). Chelsea has a majority non-white demographic with approximately 57.6% of its population identifying as not white (WPR, 2022). In addition to this, 19.1% of Chelsea residents live below the poverty line (U.S. Census, 2022). All this noise polluting infrastructure is contributing to higher risk of the previously mentioned health conditions as well as stress. Something that is not as measurable is the nature of the noise. For example, the sound of water flowing, leaves, wind, or people talking is far less cacophonic than trains, trucks, ships, and airplanes.'}/>
            <Section sectionPic={t1i3}sectionTitle={'Phoenix Arizona'} sectionContent={'In Phoenix, Arizona, the average temperature in the months of June, July and August is 41°C (Current Results, 2022). With low income and high dependance on public transportation, certain marginalized communities are exposed to the effects of heat more than others. In Phoenix the zip code 85007 has the highest heat related illnesses and is a primarily Black and Latino community with low incomes (Moutinho & Gawthrop, 2021). While this idea of nature within cities is a social construct, they do serve a purpose for controlling air and surface temperatures. While there have been programs implemented to give residents free trees for their properties if they are planted on the South or West sides of the dwelling, these programs aren’t motivated by the wellness of the communities. Instead, they stem from an emissions perspective, in hopes of making the demand on the powergrid more manageable with everyone running their air conditioning units. As far as the health-related issues, extreme heat can cause a plethora of symptoms like headaches, nasea and cramps. The 85007 zip code had nearly 10 times the amount of emergency room visits for heat related illnesses compared to the Arizona state average. While the proposed solution is trees, the issues of maintanance arise. Another solution to the public transportation dependency would be building shelters, similar to those we have in Calgary for the cold and the wind, but instead in Phoenix it would provide shade while waiting for the bus'}/>
  
            
            </div>


            <Footer topicAuth={'Keishi Exell'} topicRefs={refs}/>
            
        </div>
    )
   
}

export default Topic1